In [9]:
import numpy as np


def adjust_weights(training_with_bias, error, weights, alpha):
    delta_w0 = alpha * error[4] * training_with_bias[4,0]
    delta_w1 = alpha * error[4] * training_with_bias[4,1]
    delta_w2 = alpha * error[4] * training_with_bias[4,2]
    
    
    weights[0] += delta_w0
    weights[1] += delta_w1
    weights[2] += delta_w2
    return(weights)


def adjust_weights_1(training_with_bias, error, weights, alpha):
    delta_w0 = alpha * error[4] * training_with_bias[4,0]
    delta_w1 = alpha * error[4] * training_with_bias[4,1]
    delta_w2 = alpha * error[4] * training_with_bias[4,2]
    
    
    weights[0] -= delta_w0
    weights[1] -= delta_w1
    weights[2] -= delta_w2
    return(weights)





np.random.seed(100)

weights = 2*np.random.random((3,1))-1
print(weights)

training_data = np.array([[-3,1],[-2,2],[-1,2],[-1,3],[-1,-1],[-2,-2],[-1,-3],[2,-2],[2,1]])
training_with_bias = np.c_[np.ones(training_data.shape[0]), training_data]

output_data = np.array([[1],[1],[1],[1],[0],[0],[0],[0],[0]])
alpha=0.5
activation = np.dot(training_with_bias, weights)

output_estimate = activation

output_estimate[output_estimate > 0] = 1
output_estimate[output_estimate < 0] = 0

error = output_data - output_estimate
print(error)

new_weights = adjust_weights(training_with_bias, error, weights, alpha)
print(new_weights)

activation1 = np.dot(training_with_bias, new_weights)

output_estimate1 = activation1

output_estimate1[output_estimate1 > 0] = 1
output_estimate1[output_estimate1 < 0] = 0

error1 = output_data - output_estimate1
print(error1)


new_weights_1 = adjust_weights_1(training_with_bias, error, weights, alpha)
print(new_weights_1)

activation2 = np.dot(training_with_bias, new_weights_1)

output_estimate2 = activation2

output_estimate2[output_estimate2 > 0] = 1
output_estimate2[output_estimate2 < 0] = 0

error2 = output_data - output_estimate2
print(error2)



[[ 0.08680988]
 [-0.44326123]
 [-0.15096482]]
[[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [-1.]
 [-1.]
 [-1.]
 [ 0.]
 [ 0.]]
[[-0.41319012]
 [ 0.05673877]
 [ 0.34903518]]
[[ 1.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [-1.]]
[[ 0.08680988]
 [-0.44326123]
 [-0.15096482]]
[[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [-1.]
 [-1.]
 [-1.]
 [ 0.]
 [ 0.]]


In [50]:
np.ones(training_data.shape[0])

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [81]:
alpha=0.5

In [76]:
delta_w1 = 0.5*-1*training_with_bias[4,1]
print(delta_w1)

0.5


In [85]:
error[4]*alpha*training_with_bias[4,2]

array([0.5])

In [101]:
weights[0]

array([0.08680988])

In [102]:
type(weights)

numpy.ndarray

In [103]:
weights[0] = 3

In [104]:
print(weights)

[[ 3.        ]
 [-0.44326123]
 [-0.15096482]]


In [105]:
weights[0]+=1

In [106]:
print(weights)

[[ 4.        ]
 [-0.44326123]
 [-0.15096482]]


In [13]:
np.dot((alpha*error).T,training_with_bias)

array([[-1.5,  2. ,  3. ]])