## Implementation of XOR using Neural Networks

In [6]:
import numpy as np
np.random.seed(1900220)

In [7]:
#defining the functions
def sigmoid_fn(m):
    return 1 / (1+np.exp(-m))

def sigmoid_derivative(n):
    return n * (1 - n)

def cost_function(target, estimate):
    return (target - estimate)

In [8]:
#initializing parameters
input_data = np.array([[0,0], [0,1], [1,0], [1,1]])
output_data = np.array([[0,1,1,0]]).T

X = input_data
Y = output_data

epochs = 10000
learning_rate = 0.1
hidden_units = 3

_, input_dim = input_data.shape
_, output_dim = output_data.shape

#Weight matrix
W1 = np.random.random((input_dim, hidden_units))
W2 = np.random.random((hidden_units, output_dim))

In [11]:

for epoch in range(epochs):
    layer0 = X
    #Forward pas
    layer1 = sigmoid_fn(np.dot(layer0, W1))
    layer2 = sigmoid_fn(np.dot(layer1, W2))
    
    
    layer2_error = cost_function(Y, layer2)
    #print(layer2_error)
    #Back pass
    layer2_delta = layer2_error * sigmoid_derivative(layer2)
    layer1_delta = np.multiply(np.dot(layer2_delta, W2.T), sigmoid_derivative(layer1))
    
    W2 += learning_rate * np.dot(layer1.T,layer2_delta)
    W1 += learning_rate * np.dot(layer0.T, layer1_delta)
    
print(layer2)

[[ 0.11711926]
 [ 0.92212049]
 [ 0.92210456]
 [ 0.04754556]]


In [4]:
W1

array([[ 0.62647301,  0.91834567,  0.26287853],
       [ 0.99181846,  0.13996919,  0.68295715]])

In [5]:
W2

array([[ 0.46733072],
       [ 0.10974836],
       [ 0.33660039]])