#### Perceptron Learning
An example of pattern classification in the x-y two dimensional space using a hard limiting function of a Perceptron. We have class A with four patterns given [-3,1],[-2,2],[-1,2],[-1,3] and class B with five patterns [-1,-1],[-2,-2],[-1,-3],[2,-2],[2,1],[0,1]. An output of 1 indicates class A and an output of 0 indicates class B. 

Weights are initialized (at random) for the input features including a bias weight - so a weight vector of dimension 3 * 1 is created. The sum product of the input and weights is checked - if it is greater than 0, then the output is 1 and 0 otherwise.

There occurs an error (+1 or -1) if the calculated output is different from the required output (based on the class label for the corresponding input). 
All the three weights are adjusted by using the formula: Wnew = Wold + learning_rate * (Target Output - Actual Output) * Input (input is 1 for the bias weight).


In [31]:
def activation_fn(trainingbias,wt,output_data):
    activation = np.dot(trainingbias, wt)
    activation[activation > 0] = 1
    activation[activation <= 0] = 0
    error = output_data - activation
    return(error)

In [38]:
import numpy as np

training_data = np.array([[-3,1],[-2,2],[-1,2],[-1,3],[-1,-1],[-2,-2],[-1,-3],[2,-2],[2,1],[0,1]])
training_with_bias = np.c_[np.ones(training_data.shape[0]), training_data]
output_data = np.array([[1],[1],[1],[1],[0],[0],[0],[0],[0],[0]])

output_estimate = np.empty(shape=(output_data.shape))
output_estimate1 = np.empty(shape=(output_data.shape))


delta = np.empty(shape = (3,1))
np.random.seed(100)
#weights = np.array([[-0.75],[-1.2],[1.3]])
weights = 2*np.random.random((3,1))-1

alpha = 0.1

error = activation_fn(training_with_bias, weights, output_data)
print("error is ",error)

error_index = np.where(error!=0)[0]


while True:
    for i in error_index:
        print(i)
        delta[0,0] = error[i]*alpha*training_with_bias[i,0]
        delta[1,0] = error[i]*alpha*training_with_bias[i,1]
        delta[2,0] = error[i]*alpha*training_with_bias[i,2]  
        print("weights before update",weights)
        print("delta is",delta)
        weights += delta
        print("weights after update", weights)
        error = activation_fn(training_with_bias, weights, output_data)
        print(error)
        #print(weights)
    
    error_index = np.where(error!=0)[0]
    print("error index is",error_index)
    if(len(error_index) ==0):
        break


error is  [[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [-1.]
 [-1.]
 [-1.]
 [ 0.]
 [ 0.]
 [ 0.]]
4
training_with_bias 1.0 -1.0 -1.0
weights before update [[ 0.08680988]
 [-0.44326123]
 [-0.15096482]]
delta is [[-0.1]
 [ 0.1]
 [ 0.1]]
weights after update [[-0.01319012]
 [-0.34326123]
 [-0.05096482]]
[[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [-1.]
 [-1.]
 [-1.]
 [ 0.]
 [ 0.]
 [ 0.]]
5
training_with_bias 1.0 -2.0 -2.0
weights before update [[-0.01319012]
 [-0.34326123]
 [-0.05096482]]
delta is [[-0.1]
 [ 0.2]
 [ 0.2]]
weights after update [[-0.11319012]
 [-0.14326123]
 [ 0.14903518]]
[[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [-1.]]
6
training_with_bias 1.0 -1.0 -3.0
weights before update [[-0.11319012]
 [-0.14326123]
 [ 0.14903518]]
delta is [[ 0.]
 [-0.]
 [-0.]]
weights after update [[-0.11319012]
 [-0.14326123]
 [ 0.14903518]]
[[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [-1.]]
error index is [9]
9
training_with_bias 1.0 0.0 1.0
weights before update [[-0.11319012]
 [-0.143